FROM node:8
WORKDIR /app
COPY package.json /app
RUN npm install
COPY . /app

ENV API_SECRET=$API_SECRET

ENV API_TOKEN=$API_TOKEN

ENV CLOUDINARY_URL=$CLOUDINARY_URL

ENV DATABASE_MODE=$DATABASE_MODE

ENV DATABASE_URL=$DATABASE_URL

ENV DB_NAME=$DB_NAME

ENV DB_PASSWORD=$DB_PASSWORD

ENV LOGIN_REGEX=$LOGIN_REGEX

ENV NODE_ENV=$NODE_ENV

ENV PAPERTRAIL_API_TOKEN=$PAPERTRAIL_API_TOKEN

ENV AZURE_STORAGE_TOKEN=$AZURE_STORAGE_TOKEN

ENV AZURE_STORAGE_CONTAINER_NAME=$AZURE_STORAGE_CONTAINER_NAME

ENV AZURE_STORAGE_BLOB_NAME=$AZURE_STORAGE_BLOB_NAME

ENV ZAPIER_URL=$ZAPIER_URL

ENV DOCKER_ENV=$DOCKER_ENV

EXPOSE 3000

RUN npm run build
CMD [ "npm", "run", "docker" ]